#ifndef LORA_CONFIG_H_
#define LORA_CONFIG_H_

#define RF_FREQUENCY 915000000 // change to 865000000 for India
#define TX_OUTPUT_POWER 14
#define LORA_BANDWIDTH 0
#define LORA_SPREADING_FACTOR 7
#define LORA_CODINGRATE 1
#define LORA_PREAMBLE_LENGTH 8
#define LORA_FIX_LENGTH_PAYLOAD_ON false
#define LORA_IQ_INVERSION_ON false
#define RX_TIMEOUT_VALUE 1000

#endif // LORA_CONFIG_H_
