microClimate Monitoring Remote Node [Firmware]: BME680_Class Class Reference
BME680_Class Class Reference
Main BME680 class for the temperature / humidity / pressure sensor.
#include <BME680.h>
Public Member Functions
BME680_Class ()
~BME680_Class ()
bool begin ()
bool begin (const uint32_t i2cSpeed)
bool begin (const uint8_t chipSelect)
bool begin (const uint32_t i2cSpeed, const uint8_t i2cAddress)
bool begin (const uint8_t chipSelect, const uint8_t mosi, const uint8_t miso, const uint8_t sck)
uint8_t setOversampling (const uint8_t sensor, const uint8_t sampling=UINT8_MAX)
bool setGas (uint16_t GasTemp, uint16_t GasMillis)
uint8_t setIIRFilter (const uint8_t iirFilterSetting=UINT8_MAX)
uint8_t getSensorData (int32_t &temp, int32_t &hum, int32_t &press, int32_t &gas, const bool waitSwitch=true)
uint8_t getI2CAddress () const
void reset ()
bool measuring ()
true if currently measuring
void triggerMeasurement ()
trigger a measurement
Private Member Functions
bool commonInitialization ()
Common initialization code.
uint8_t readByte (const uint8_t addr)
Read byte from register address.
uint8_t readSensors (const bool waitSwitch)
read the registers in one burst
void waitForReadings ()
Wait for readings to finish.
void getCalibration ()
Load calibration from registers.
template<typename T>
uint8_t & getData (TwoWire &wire, const uint8_t addr, T &value) const
template<typename T>
uint8_t & putData (TwoWire &wire, const uint8_t addr, const T &value) const
Private Attributes
TwoWire wire = TwoWire(1)
uint8_t _I2CAddress = 0
Default is I2C address is unknown.
uint16_t _I2CSpeed = 0
Default is I2C speed is unknown.
uint8_t _cs
uint8_t _sck
uint8_t _mosi
uint8_t _miso
Hardware and software SPI pins.
uint8_t _H6
uint8_t _P10
uint8_t _res_heat_range
unsigned configuration vars
int8_t _H3
int8_t _H4
int8_t _H5
int8_t _H7
int8_t _G1
int8_t _G3
int8_t _T3
int8_t _P3
int8_t _P6
int8_t _P7
int8_t _res_heat
int8_t _rng_sw_err
signed configuration vars
uint16_t _H1
uint16_t _H2
uint16_t _T1
uint16_t _P1
unsigned 16bit configuration vars
int16_t _G2
int16_t _T2
int16_t _P2
int16_t _P4
int16_t _P5
int16_t _P8
int16_t _P9
signed 16bit configuration vars
int32_t _tfine
int32_t _Temperature
int32_t _Pressure
int32_t _Humidity
int32_t _Gas
signed 32bit configuration vars
Detailed Description
Main BME680 class for the temperature / humidity / pressure sensor.
Definition at line 144 of file BME680.h.
Constructor & Destructor Documentation
BME680_Class()
BME680_Class::BME680_Class ()
Class constructor
Currently empty and unused
Definition at line 97 of file BME680.cpp.
{
} // of class constructor
~BME680_Class()
BME680_Class::~BME680_Class ()
Class destructor
Currently empty and unused
Definition at line 103 of file BME680.cpp.
{
} // of class destructor
Member Function Documentation
begin() [1/5]
bool BME680_Class::begin ()
starts communications with device (overloaded)
When called with no parameters the I2C protocol with I2C_STANDARD_MODE speed is selected. The I2C network is searched for the first BME680 device. return "true" if successful otherwise false
Definition at line 113 of file BME680.cpp.
{
    return begin(
        I2C_STANDARD_MODE,
        0); // Initialize I2C with standard speed, allow any i2c address
} // of method begin()
References begin(), and I2C_STANDARD_MODE.
Referenced by begin(), begin(), begin(), and reset().
begin() [2/5]
bool BME680_Class::begin (const uint32_t i2cSpeed)
starts communications with device (overloaded)
When called with a 32-bit parameter it is assumed that the I2C protocol is to be used and the speed setting is determined by the parameter.
Parameters
[in] i2cSpeed I2C Speed value return "true" if successful otherwise false
Definition at line 125 of file BME680.cpp.
{
    return begin(i2cSpeed,
                 0); // Initialize I2C with given speed, allow any i2c address
} // of method begin()
References begin().
begin() [3/5]
bool BME680_Class::begin (const uint32_t i2cSpeed, const uint8_t i2cAddress)
starts communications with device (overloaded)
When called with a 32-bit parameter it is assumed that the I2C protocol is to be used and the speed setting is determined by the parameter. If the i2cAddress is 0 then check both, otherwise check only only the specified address
Parameters
[in] i2cSpeed I2C Speed value
[in] i2cAddress I2C Address, use 0 to self-determine return "true" if successful otherwise false
Definition at line 136 of file BME680.cpp.
{
    wire.begin(DEFAULT_BME680_SDA, DEFAULT_BME680_SCL,
               i2cSpeed);    // Start I2C as master
    wire.setClock(i2cSpeed); // and set bus speed
    _I2CSpeed = i2cSpeed;
    for (_I2CAddress = BME680_I2C_MIN_ADDRESS;
         _I2CAddress <= BME680_I2C_MAX_ADDRESS;
         _I2CAddress++) { // Loop through all I2C addresses
        if (i2cAddress == 0 ||
            _I2CAddress == i2cAddress) {         // Only check if relevant
            wire.beginTransmission(_I2CAddress); // Check for BME680 here
            if (wire.endTransmission() ==
                0) { // We have found a device that could be
                return commonInitialization(); // a BME680, so perform common
                                               // init
            } // of if-then we have found a device
        } // of if-then check all or a specific address
    } // of for-next each I2C address loop
    _I2CAddress = 0; // Set to denote no device found
    _I2CSpeed = 0;   // Set to denote no device found
    return false;    // return failure if we get here
} // of method begin()
References _I2CAddress, _I2CSpeed, BME680_I2C_MAX_ADDRESS, BME680_I2C_MIN_ADDRESS, commonInitialization(), DEFAULT_BME680_SCL, DEFAULT_BME680_SDA, and wire.
begin() [4/5]
bool BME680_Class::begin (const uint8_t chipSelect)
starts communications with device (overloaded)
When called with a single 8-bit parameter is assumed that hardware SPI is to be used if the value is not 0x76 or 0x77, in which case it is assumed that it is the I2C addr
Parameters
[in] chipSelect Arduino Pin number for the Slave-Select pin or the I2C address return "true" if successful otherwise false
Definition at line 168 of file BME680.cpp.
{
    if (chipSelect == BME680_I2C_MIN_ADDRESS ||
        chipSelect == BME680_I2C_MAX_ADDRESS) {
        // If 0x76 or 0x77 then we have I2C
        return begin(I2C_STANDARD_MODE,
                     chipSelect); // Std speed with explicit address
    } // if-then we have an I2C call
    _cs = chipSelect;              // Store value for future use
    digitalWrite(_cs, HIGH);       // High means ignore master
    pinMode(_cs, OUTPUT);          // Make the chip select pin output
    SPI.begin();                   // Start hardware SPI
    return commonInitialization(); // Perform common initialization
} // of method begin()
References _cs, begin(), BME680_I2C_MAX_ADDRESS, BME680_I2C_MIN_ADDRESS, commonInitialization(), and I2C_STANDARD_MODE.
begin() [5/5]
bool BME680_Class::begin (const uint8_t chipSelect, const uint8_t mosi, const uint8_t miso, const uint8_t sck)
starts communications with device (overloaded)
When called with 4 parameters then software SPI is assumed
Parameters
[in] chipSelect Arduino Pin number for the Slave-Select pin
[in] mosi Arduino Pin number for the Master-out-Slave-in pin
[in] miso Arduino Pin number for the Master-in-Slave-out pin
[in] sck Arduino Pin number for the System clock pin return "true" if successful otherwise false
Definition at line 189 of file BME680.cpp.
{
    _cs = chipSelect;
    _mosi = mosi;
    _miso = miso;
    _sck = sck;                    // Store SPI pins
    digitalWrite(_cs, HIGH);       // High means ignore master
    pinMode(_cs, OUTPUT);          // Make the chip select pin output
    pinMode(_sck, OUTPUT);         // Make system clock pin output
    pinMode(_mosi, OUTPUT);        // Make master-out slave-in output
    pinMode(_miso, INPUT);         // Make master-in slave-out input
    return commonInitialization(); // Perform common initialization
} // of method begin()
References _cs, _miso, _mosi, _sck, and commonInitialization().
commonInitialization()
bool BME680_Class::commonInitialization () private
Common initialization code.
Common BME680 initialization function
Called from all of the overloaded "begin()" functions once the communications protocol has been selected return "true" if successful otherwise false
Definition at line 211 of file BME680.cpp.
{
    uint8_t SPI_Register = readByte(BME680_SPI_REGISTER); // Read SPI reg. byte
    if (_I2CAddress == 0 &&
        bitRead(SPI_Register,
                BME680_SPI_MEM_PAGE_POSITION)) { // Wrong mode for ID
        bitWrite(SPI_Register, BME680_SPI_MEM_PAGE_POSITION,
                 0); // Turn off Page bit to go to Page 0
        putData(wire, BME680_SPI_REGISTER,
                SPI_Register); // Write value to register
    } // of if-then we are in SPI mode
    if (readByte(BME680_CHIPID_REGISTER) ==
        BME680_CHIPID) {        // check for correct chip id
        getCalibration();       // get the calibration values
        if (_I2CAddress == 0) { // If using SPI, switch to correct
            bitWrite(SPI_Register, BME680_SPI_MEM_PAGE_POSITION,
                     1); // Page "1" again
            putData(wire, BME680_SPI_REGISTER,
                    SPI_Register); // Update register value
        } // of if-then SPI mode
        uint8_t workRegister = readByte(
            BME680_CONTROL_MEASURE_REGISTER); // Read the control measure
        putData(wire, BME680_CONTROL_MEASURE_REGISTER,
                (uint8_t)(workRegister | 1)); // Trigger 1st measurement
        return true;
    } // of if-then device is really a BME680
    else
        return false;
} // of method commonInitialization
References _I2CAddress, BME680_CHIPID, BME680_CHIPID_REGISTER, BME680_CONTROL_MEASURE_REGISTER, BME680_SPI_MEM_PAGE_POSITION, BME680_SPI_REGISTER, getCalibration(), putData(), readByte(), and wire.
Referenced by begin(), begin(), and begin().
getCalibration()
void BME680_Class::getCalibration () private
Load calibration from registers.
reads the calibration register data into local variables for use in converting readings
The calibration registers are read into a temporary array and then parsed into the appropriate calibration variables, this was taken from the example BOSCH software and minimizes register reads, but makes it rather difficult to read. This will be redone for legibility at some point in the future param[in] addr Address of device return single byte read
Definition at line 274 of file BME680.cpp.
{
    /*************************************
    ** Temperature related coefficients **
    *************************************/
    uint8_t coeff_arr1[BME680_COEFF_SIZE1] = {
        0}; // Define temp array 1 and initialize with 0x
    uint8_t coeff_arr2[BME680_COEFF_SIZE2] = {
        0}; // Define temp array 2 and initialize with 0s
    getData(wire, BME680_COEFF_START_ADDRESS1,
            coeff_arr1); // Split reading registers into 2
    getData(wire, BME680_COEFF_START_ADDRESS2,
            coeff_arr2); // one 25 bytes and the other 16
    _T1 = (uint16_t)(CONCAT_BYTES(coeff_arr2[BME680_T1_MSB_REG],
                                  coeff_arr2[BME680_T1_LSB_REG]));
    _T2 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_T2_MSB_REG],
                                 coeff_arr1[BME680_T2_LSB_REG]));
    _T3 = (int8_t)(coeff_arr1[BME680_T3_REG]);
    /*************************************
    ** Pressure related coefficients    **
    *************************************/
    _P1 = (uint16_t)(CONCAT_BYTES(coeff_arr1[BME680_P1_MSB_REG],
                                  coeff_arr1[BME680_P1_LSB_REG]));
    _P2 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_P2_MSB_REG],
                                 coeff_arr1[BME680_P2_LSB_REG]));
    _P3 = (int8_t)coeff_arr1[BME680_P3_REG];
    _P4 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_P4_MSB_REG],
                                 coeff_arr1[BME680_P4_LSB_REG]));
    _P5 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_P5_MSB_REG],
                                 coeff_arr1[BME680_P5_LSB_REG]));
    _P6 = (int8_t)(coeff_arr1[BME680_P6_REG]);
    _P7 = (int8_t)(coeff_arr1[BME680_P7_REG]);
    _P8 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_P8_MSB_REG],
                                 coeff_arr1[BME680_P8_LSB_REG]));
    _P9 = (int16_t)(CONCAT_BYTES(coeff_arr1[BME680_P9_MSB_REG],
                                 coeff_arr1[BME680_P9_LSB_REG]));
    _P10 = (uint8_t)(coeff_arr1[BME680_P10_REG]);
    /**********************************
    ** Humidity related coefficients **
    **********************************/
    _H1 = (uint16_t)(((uint16_t)coeff_arr2[BME680_H1_MSB_REG]
                      << BME680_HUM_REG_SHIFT_VAL) |
                     ((coeff_arr2[BME680_H1_LSB_REG] >>
                       BME680_HUM_REG_SHIFT_VAL) &
                      BME680_BIT_H1_DATA_MSK));
    _H2 = (uint16_t)(((uint16_t)coeff_arr2[BME680_H2_MSB_REG]
                      << BME680_HUM_REG_SHIFT_VAL) |
                     ((coeff_arr2[BME680_H2_LSB_REG] >>
                       BME680_HUM_REG_SHIFT_VAL) &
                      BME680_BIT_H1_DATA_MSK));
    _H3 = (int8_t)coeff_arr2[BME680_H3_REG];
    _H4 = (int8_t)coeff_arr2[BME680_H4_REG];
    _H5 = (int8_t)coeff_arr2[BME680_H5_REG];
    _H6 = (uint8_t)coeff_arr2[BME680_H6_REG];
    _H7 = (int8_t)coeff_arr2[BME680_H7_REG];
    /************************************
    ** Gas heater related coefficients **
    ************************************/
    _G1 = (int8_t)coeff_arr2[BME680_GH1_REG];
    _G2 = (int16_t)(CONCAT_BYTES(coeff_arr2[BME680_GH2_MSB_REG],
                                 coeff_arr2[BME680_GH2_LSB_REG]));
    _G3 = (int8_t)coeff_arr2[BME680_GH3_REG];
    uint8_t temp_var = 0;
    getData(wire, BME680_ADDR_RES_HEAT_RANGE_ADDR, temp_var);
    _res_heat_range = ((temp_var & BME680_RHRANGE_MSK) / 16);
    getData(wire, BME680_ADDR_RES_HEAT_VAL_ADDR, temp_var);
    _res_heat = (int8_t)temp_var;
    getData(wire, BME680_ADDR_RANGE_SW_ERR_ADDR, temp_var);
    _rng_sw_err = ((int8_t)temp_var & (int8_t)BME680_RSERROR_MSK) / 16;
} // of method getCalibration()
References _G1, _G2, _G3, _H1, _H2, _H3, _H4, _H5, _H6, _H7, _P1, _P10, _P2, _P3, _P4, _P5, _P6, _P7, _P8, _P9, _res_heat, _res_heat_range, _rng_sw_err, _T1, _T2, _T3, BME680_ADDR_RANGE_SW_ERR_ADDR, BME680_ADDR_RES_HEAT_RANGE_ADDR, BME680_ADDR_RES_HEAT_VAL_ADDR, BME680_BIT_H1_DATA_MSK, BME680_COEFF_SIZE1, BME680_COEFF_SIZE2, BME680_COEFF_START_ADDRESS1, BME680_COEFF_START_ADDRESS2, BME680_GH1_REG, BME680_GH2_LSB_REG, BME680_GH2_MSB_REG, BME680_GH3_REG, BME680_H1_LSB_REG, BME680_H1_MSB_REG, BME680_H2_LSB_REG, BME680_H2_MSB_REG, BME680_H3_REG, BME680_H4_REG, BME680_H5_REG, BME680_H6_REG, BME680_H7_REG, BME680_HUM_REG_SHIFT_VAL, BME680_P10_REG, BME680_P1_LSB_REG, BME680_P1_MSB_REG, BME680_P2_LSB_REG, BME680_P2_MSB_REG, BME680_P3_REG, BME680_P4_LSB_REG, BME680_P4_MSB_REG, BME680_P5_LSB_REG, BME680_P5_MSB_REG, BME680_P6_REG, BME680_P7_REG, BME680_P8_LSB_REG, BME680_P8_MSB_REG, BME680_P9_LSB_REG, BME680_P9_MSB_REG, BME680_RHRANGE_MSK, BME680_RSERROR_MSK, BME680_T1_LSB_REG, BME680_T1_MSB_REG, BME680_T2_LSB_REG, BME680_T2_MSB_REG, BME680_T3_REG, CONCAT_BYTES, getData(), and wire.
Referenced by commonInitialization().
getData()
template<typename T> uint8_t & BME680_Class::getData (TwoWire & wire, const uint8_t addr, T & value) const inline private
functions
Declare the getData and putData methods as template functions. All device I/O is done through these two functions regardless of whether I2C, hardware SPI or software SPI is being used. The two functions are designed so that only the address and a variable are passed in and the functions determine the size of the parameter variable and reads or writes that many bytes. So if a read is called using a character array[10] then 10 bytes are read, if called with a int8 then only one byte is read. The return value, if used, is the number of bytes read or written. Since this is implemented by using template function definitions, they need to be defined in this header file rather than in the c++ program library file. The "getData()" function is currently not used in the library directly, but the function "readByte()" is used which calls the getData(). The "putData()" is called directly in the code.
Template for reading from I2C or SPI using any data type
As a template it can support compile-time data type definitions
Parameters
[in] addr Memory address
[in] value Data Type "T" to read
Returns
Size of data read in bytes
Definition at line 214 of file BME680.h.
{
        uint8_t *bytePtr = (uint8_t *)&value;  // Pointer to structure beginning
        static uint8_t structSize = sizeof(T); // Number of bytes in structure
        if (_I2CAddress) // Using I2C if address is non-zero
        {                //
            wire.beginTransmission(_I2CAddress); // Address the I2C device
            wire.write(addr);       // Send register address to read
            wire.endTransmission(); // Close transmission
            wire.requestFrom(_I2CAddress, sizeof(T)); // Request 1 byte of data
            structSize = wire.available(); // Use the actual number of bytes
            for (uint8_t i = 0; i < structSize; i++)
                *bytePtr++ = wire.read(); // loop for each byte to be read
        } //
        else               //
        {                  //
            if (_sck == 0) // if sck is zero then hardware SPI
            {              //
                SPI.beginTransaction(
                    SPISettings(SPI_HERZ, MSBFIRST,
                                SPI_MODE0)); // Start the SPI transaction
                digitalWrite(_cs, LOW);      // Tell BME680 to listen up
                SPI.transfer(addr | 0x80);   // bit 7 is high, so read a byte
                for (uint8_t i = 0; i < structSize; i++)
                    *bytePtr++ =
                        SPI.transfer(0); // loop for each byte to be read
                digitalWrite(_cs, HIGH); // Tell BME680 to stop listening
                SPI.endTransaction();    // End the transaction
            } else {                     // otherwise we are using soft SPI
                int8_t i, j;             // Loop variables
                uint8_t reply;           // return byte for soft SPI transfer
                digitalWrite(_cs, LOW);  // Tell BME680 to listen up
                for (j = 7; j >= 0; j--) // First send the address byte
                {
                    digitalWrite(_sck, LOW); // set the clock signal
                    digitalWrite(_mosi, ((addr) | 0x80) &
                                            (1 << j)); // set the MOSI pin state
                    digitalWrite(_sck, HIGH);          // reset the clock signal
                } // of for-next each bit
                for (i = 0; i < structSize; i++) // Loop for each byte to read
                {                                //
                    reply = 0;                   // reset our return byte
                    for (j = 7; j >= 0; j--) // Now read the data at that byte
                    {                        //
                        reply <<= 1;         // shift buffer one bit left
                        digitalWrite(_sck,
                                     LOW); // set and reset the clock signal
                        digitalWrite(_sck,
                                     HIGH); // pin to get the next MISO bit
                        if (digitalRead(_miso))
                            reply |= 1; // read the MISO bit, add to reply
                    } // of for-next each bit
                    *bytePtr++ = reply; // Add byte just read to return data
                } // of for-next each byte to be read
                digitalWrite(_cs, HIGH); // Tell BME680 to stop listening
            } // of  if-then-else we are using hardware SPI
        } // of if-then-else we are using I2C
        return (structSize);
    } // of method getData()
References _cs, _I2CAddress, _miso, _mosi, _sck, SPI_HERZ, and wire.
Referenced by getCalibration(), readByte(), and readSensors().
getI2CAddress()
uint8_t BME680_Class::getI2CAddress () const
Returns the I2C address of the BME680 return I2C Address from private variables
Definition at line 465 of file BME680.cpp.
{
    return (_I2CAddress);
} // of method getI2CAddress()
References _I2CAddress.
getSensorData()
uint8_t BME680_Class::getSensorData (int32_t & temp, int32_t & hum, int32_t & press, int32_t & gas, const bool waitSwitch = true)
Returns the most recent temperature, humidity and pressure readings param[out] temp Temperature reading param[out] hum Humidity reading param[out] press Pressure reading param[out] gas Gas reading param[in] waitSwitch (Optional) When set will not return until reading is finished
Definition at line 448 of file BME680.cpp.
{
    uint8_t status =
        readSensors(waitSwitch); // Get compensated data from BME680
    temp = _Temperature;         // Copy global variables to parameters
    hum = _Humidity;             // Copy global variables to parameters
    press = _Pressure;           // Copy global variables to parameters
    gas = _Gas;                  // Copy global variables to parameters
    return (status);             // Nonzero if gas is invalid or unstable
} // of method getSensorData()
References _Gas, _Humidity, _Pressure, _Temperature, and readSensors().
measuring()
bool BME680_Class::measuring ()
true if currently measuring
Returns whether the BME680 is currently measuring return "true" if a measurement is active, otherwise "false"
Definition at line 658 of file BME680.cpp.
{
    bool result(false);
    if ((readByte(BME680_STATUS_REGISTER) &
         _BV(BME680_MEASURING_BIT_POSITION)) != 0) {
        result = true;
    } // if-then device is currently measuring
    return result;
} // of method "measuring()"
References _BV, BME680_MEASURING_BIT_POSITION, BME680_STATUS_REGISTER, and readByte().
Referenced by waitForReadings().
putData()
template<typename T> uint8_t & BME680_Class::putData (TwoWire & wire, const uint8_t addr, const T & value) const inline private
Template for writing to I2C or SPI using any data type
As a template it can support compile-time data type definitions
Parameters
[in] addr Memory address
[in] value Data Type "T" to write
Returns
Size of data written in bytes
Definition at line 281 of file BME680.h.
{
        const uint8_t *bytePtr =
            (const uint8_t *)&value;           // Pointer to structure beginning
        static uint8_t structSize = sizeof(T); // Number of bytes in structure
        if (_I2CAddress) // Using I2C if address is non-zero
        {                //
            wire.beginTransmission(_I2CAddress); // Address the I2C device
            wire.write(addr); // Send register address to write
            for (uint8_t i = 0; i < sizeof(T); i++)
                wire.write(*bytePtr++); // loop for each byte to be written
            wire.endTransmission();     // Close transmission
        } else {
            if (_sck == 0) // if sck is zero then hardware SPI
            {
                SPI.beginTransaction(
                    SPISettings(SPI_HERZ, MSBFIRST,
                                SPI_MODE0)); // start the SPI transaction
                digitalWrite(_cs, LOW);      // Tell BME680 to listen up
                SPI.transfer(addr & ~0x80);  // bit 7 is low, so write a byte
                for (uint8_t i = 0; i < structSize; i++) {
                    SPI.transfer(*bytePtr++);
                } // loop for each byte to be written
                digitalWrite(_cs, HIGH); // Tell BME680 to stop listening
                SPI.endTransaction();    // End the transaction
            } else                       // Otherwise soft SPI is used
            {
                int8_t i, j;   // Loop variables
                uint8_t reply; // return byte for soft SPI transfer
                for (i = 0; i < structSize; i++) // Loop for each byte to read
                {
                    reply = 0;               // reset our return byte
                    digitalWrite(_cs, LOW);  // Tell BME680 to listen up
                    for (j = 7; j >= 0; j--) // First send the address byte
                    {
                        digitalWrite(_sck, LOW); // set the clock signal
                        digitalWrite(_mosi,
                                     (addr & ~0x80) &
                                         (1 << j)); // set the MOSI pin state
                        digitalWrite(_sck, HIGH);   // reset the clock signal
                    } // of for-next each bit
                    for (j = 7; j >= 0; j--) // Now read the data at that byte
                    {
                        reply <<= 1;             // shift buffer one bit left
                        digitalWrite(_sck, LOW); // set the clock signal
                        digitalWrite(_mosi,
                                     *bytePtr &
                                         (1 << j)); // set the MOSI pin state
                        digitalWrite(_sck, HIGH);   // reset the clock signal
                    } // of for-next each bit
                    digitalWrite(_cs, HIGH); // Tell BME680 to stop listening
                    bytePtr++;               // go to next byte to write
                } // of for-next each byte to be read
            } // of  if-then-else we are using hardware SPI
        } // of if-then-else we are using I2C
        return (structSize);
    } // of method putData()
References _cs, _I2CAddress, _mosi, _sck, SPI_HERZ, and wire.
Referenced by commonInitialization(), reset(), setGas(), setIIRFilter(), setOversampling(), and triggerMeasurement().
readByte()
uint8_t BME680_Class::readByte (const uint8_t addr) private
Read byte from register address.
Read a single byte from the given address
interlude function to the "getData()" function. This is called so that the return value is the byte of data that has just been read rather than the number of bytes read returned by "getData()" param[in] addr Address of device return single byte of read from addr
Definition at line 245 of file BME680.cpp.
{
    uint8_t returnValue;              // Storage for returned value
    getData(wire, addr, returnValue); // Read just one byte
    return (returnValue);             // Return byte just read
} // of method readByte()
References getData(), and wire.
Referenced by commonInitialization(), measuring(), setGas(), setIIRFilter(), setOversampling(), and triggerMeasurement().
readSensors()
uint8_t BME680_Class::readSensors (const bool waitSwitch) private
read the registers in one burst
reads all 4 sensor values from the registers in one operation and then proceeds to convert the raw temperature, pressure & humidity readings into standard metric units
The formula is written in the BME680's documentation but the math used below was taken from Adafruit's Adafruit_BME680_Library at https://github.com/adafruit/Adafruit_BME680. I think it can be refactored into more efficient code at some point in the future, but it does work correctly. param[in] waitSwitch (Optional) When set will not return until reading is finished
Lookup table for the possible gas range values
Definition at line 472 of file BME680.cpp.
{
    const uint32_t lookupTable1[16] = {
        UINT32_C(2147483647), UINT32_C(2147483647), UINT32_C(2147483647),
        UINT32_C(2147483647), UINT32_C(2147483647), UINT32_C(2126008810),
        UINT32_C(2147483647), UINT32_C(2130303777), UINT32_C(2147483647),
        UINT32_C(2147483647), UINT32_C(2143188679), UINT32_C(2136746228),
        UINT32_C(2147483647), UINT32_C(2126008810), UINT32_C(2147483647),
        UINT32_C(2147483647)};
    const uint32_t lookupTable2[16] = {
        UINT32_C(4096000000), UINT32_C(2048000000), UINT32_C(1024000000),
        UINT32_C(512000000),  UINT32_C(255744255),  UINT32_C(127110228),
        UINT32_C(64000000),   UINT32_C(32258064),   UINT32_C(16016016),
        UINT32_C(8000000),    UINT32_C(4000000),    UINT32_C(2000000),
        UINT32_C(1000000),    UINT32_C(500000),     UINT32_C(250000),
        UINT32_C(125000)};
    uint8_t buff[15], gas_range = 0; // declare array for registers
    int64_t var1, var2, var3, var4, var5, var6, temp_scaled; // Work variables
    uint32_t adc_temp, adc_pres;   // Raw ADC temperature and pressure
    uint16_t adc_hum, adc_gas_res; // Raw ADC humidity and gas
    if (waitSwitch)
        waitForReadings(); // Doesn't return until the readings are finished
    getData(wire, BME680_STATUS_REGISTER, buff); // read all 15 bytes in one go
    adc_pres =
        (uint32_t)(((uint32_t)buff[2] << 12) | ((uint32_t)buff[3] << 4) |
                   ((uint32_t)buff[4] >> 4)); // put the 3 bytes of Pressure
    adc_temp =
        (uint32_t)(((uint32_t)buff[5] << 12) | ((uint32_t)buff[6] << 4) |
                   ((uint32_t)buff[7] >> 4)); // put the 3 bytes of Temperature
    adc_hum = (uint16_t)(((uint32_t)buff[8] << 8) |
                         (uint32_t)buff[9]); // put the 2 bytes of Humidity
    adc_gas_res =
        (uint16_t)((uint32_t)buff[13] << 2 |
                   (((uint32_t)buff[14]) >> 6)); // put the 2 bytes of Gas
    gas_range = buff[14] & 0X0F;                 // Retrieve the range
                                 //*******************************//
                                 // First compute the temperature //
                                 //*******************************//
    var1 = ((int32_t)adc_temp >> 3) -
           ((int32_t)_T1 << 1);               // Perform calibration/adjustment
    var2 = (var1 * (int32_t)_T2) >> 11;       // of Temperature values according
    var3 = ((var1 >> 1) * (var1 >> 1)) >> 12; // to formula defined by Bosch
    var3 = ((var3) * ((int32_t)_T3 << 4)) >> 14;
    _tfine = (int32_t)(var2 + var3);
    _Temperature = (int16_t)(((_tfine * 5) + 128) >> 8);
    //*******************************//
    // Now compute the pressure      //
    //*******************************//
    var1 = (((int32_t)_tfine) >> 1) - 64000;
    var2 = ((((var1 >> 2) * (var1 >> 2)) >> 11) * (int32_t)_P6) >> 2;
    var2 = var2 + ((var1 * (int32_t)_P5) << 1);
    var2 = (var2 >> 2) + ((int32_t)_P4 << 16);
    var1 = (((((var1 >> 2) * (var1 >> 2)) >> 13) * ((int32_t)_P3 << 5)) >> 3) +
           (((int32_t)_P2 * var1) >> 1);
    var1 = var1 >> 18;
    var1 = ((32768 + var1) * (int32_t)_P1) >> 15;
    _Pressure = 1048576 - adc_pres;
    _Pressure = (int32_t)((_Pressure - (var2 >> 12)) * ((uint32_t)3125));
    if (_Pressure >= INT32_C(0x40000000)) // Issue #26
        _Pressure = ((_Pressure / (uint32_t)var1) << 1);
    else
        _Pressure = ((_Pressure << 1) / (uint32_t)var1);
    var1 = ((int32_t)_P9 *
            (int32_t)(((_Pressure >> 3) * (_Pressure >> 3)) >> 13)) >>
           12;
    var2 = ((int32_t)(_Pressure >> 2) * (int32_t)_P8) >> 13;
    var3 = ((int32_t)(_Pressure >> 8) * (int32_t)(_Pressure >> 8) *
            (int32_t)(_Pressure >> 8) * (int32_t)_P10) >>
           17;
    _Pressure = (int32_t)(_Pressure) +
                ((var1 + var2 + var3 + ((int32_t)_P7 << 7)) >> 4);
    //**********************//
    // Compute the humidity //
    //**********************//
    temp_scaled = (((int32_t)_tfine * 5) + 128) >> 8;
    var1 = (int32_t)(adc_hum - ((int32_t)((int32_t)_H1 << 4))) -
           (((temp_scaled * (int32_t)_H3) / ((int32_t)100)) >> 1);
    var2 =
        ((int32_t)_H2 *
         (((temp_scaled * (int32_t)_H4) / ((int32_t)100)) +
          (((temp_scaled * ((temp_scaled * (int32_t)_H5) / ((int32_t)100))) >>
            6) /
           ((int32_t)100)) +
          (int32_t)(1 << 14))) >>
        10;
    var3 = var1 * var2;
    var4 = (int32_t)_H6 << 7;
    var4 = ((var4) + ((temp_scaled * (int32_t)_H7) / ((int32_t)100))) >> 4;
    var5 = ((var3 >> 14) * (var3 >> 14)) >> 10;
    var6 = (var4 * var5) >> 1;
    _Humidity = (((var3 + var6) >> 10) * ((int32_t)1000)) >> 12;
    if (_Humidity > 100000) /* Cap at 100%rH */
        _Humidity = 100000;
    else if (_Humidity < 0)
        _Humidity = 0;
    //**********************//
    // Compute the Gas      //
    //**********************//
    uint64_t uvar2;
    var1 = (int64_t)((1340 + (5 * (int64_t)_rng_sw_err)) *
                     ((int64_t)lookupTable1[gas_range])) >>
           16;
    uvar2 =
        (((int64_t)((int64_t)adc_gas_res << 15) - (int64_t)(16777216)) + var1);
    var3 = (((int64_t)lookupTable2[gas_range] * (int64_t)var1) >> 9);
    _Gas = (uint32_t)((var3 + ((int64_t)uvar2 >> 1)) / (int64_t)uvar2);
    triggerMeasurement(); // trigger the next measurement
    return (buff[14] &
            0X30); // Return nonzero if gas or heat stabilization is invalid
} // of method readSensors()
References _Gas, _H1, _H2, _H3, _H4, _H5, _H6, _H7, _Humidity, _P1, _P10, _P2, _P3, _P4, _P5, _P6, _P7, _P8, _P9, _Pressure, _rng_sw_err, _T1, _T2, _T3, _Temperature, _tfine, BME680_STATUS_REGISTER, getData(), triggerMeasurement(), waitForReadings(), and wire.
Referenced by getSensorData().
reset()
void BME680_Class::reset ()
Performs a device reset
Definition at line 257 of file BME680.cpp.
{
    putData(wire, BME680_SOFTRESET_REGISTER,
            BME680_RESET_CODE); // write reset code to device
    delay(2);                   // Datasheet states 2ms Start-up time
    if (_I2CAddress) {          // Branch depending on if using I2C or SPI
        begin(_I2CSpeed, _I2CAddress); // If I2C start device with same settings
    } else {
        if (_sck) { // If _sck is set the use software SPI
            begin(_cs, _mosi, _miso, _sck); // Use software SPI again
        } else {
            begin(_cs); // otherwise it must be hardware SPI
        } // if-then-else using sw or hw SPI
    } // if-then-else using I2C
} // of method reset()
References _cs, _I2CAddress, _I2CSpeed, _miso, _mosi, _sck, begin(), BME680_RESET_CODE, BME680_SOFTRESET_REGISTER, putData(), and wire.
setGas()
bool BME680_Class::setGas (uint16_t GasTemp, uint16_t GasMillis)
sets the gas measurement target temperature and heating time param[in] GasTemp Target temperature in Celsius param[in] GasMillis Milliseconds to turn on heater return Always returns "true"
Definition at line 602 of file BME680.cpp.
{
    waitForReadings(); // Ensure any active reading is finished
    uint8_t gasRegister =
        readByte(BME680_CONTROL_GAS_REGISTER2); // Read current register values
    if (GasTemp == 0 || GasMillis == 0) {
        // If either input variable is zero //
        putData(wire, BME680_CONTROL_GAS_REGISTER1,
                (uint8_t)B00001000); // Turn off gas heater
        putData(
            wire, BME680_CONTROL_GAS_REGISTER2,
            (uint8_t)(gasRegister & B11101111)); // Turn off gas measurements
    } else {
        putData(wire, BME680_CONTROL_GAS_REGISTER1,
                (uint8_t)0); // Turn off heater bit to turn on
        uint8_t heatr_res;
        int32_t var1, var2, var3, var4, var5, heatr_res_x100;
        if (GasTemp < 200)
            GasTemp = 200;
        else if (GasTemp > 400)
            GasTemp = 400; // Clamp temperature to min/max
        var1 = (((int32_t)(_Temperature / 100) * _H3) / 1000) << 8;
        var2 =
            (_G1 + 784) * (((((_G2 + 154009) * GasTemp * 5) / 100) + 3276800) /
                           10); // Issue #26
        var3 = var1 + (var2 / 2);
        var4 = (var3 / (_res_heat_range + 4));
        var5 = (131 * _res_heat) + 65536;
        heatr_res_x100 = (int32_t)(((var4 / var5) - 250) * 34);
        heatr_res = (uint8_t)((heatr_res_x100 + 50) / 100);
        putData(wire, BME680_GAS_HEATER_REGISTER0, heatr_res);
        uint8_t factor = 0;
        uint8_t durval;
        if (GasMillis >= 0xfc0)
            durval = 0xff; // Max duration
        else {
            while (GasMillis > 0x3F) {
                GasMillis = GasMillis >> 2;
                factor += 1;
            } // of while loop
            durval = (uint8_t)(GasMillis + (factor * 64));
        } // of if-then-else duration exceeds max
        putData(wire, BME680_CONTROL_GAS_REGISTER1,
                (uint8_t)0); // then turn off gas heater
        putData(wire, BME680_GAS_DURATION_REGISTER0, durval);
        putData(wire, BME680_CONTROL_GAS_REGISTER2,
                (uint8_t)(gasRegister | B00010000));
    } // of if-then-else turn gas measurements on or off
    return true;
} // of method setGas()
References _G1, _G2, _H3, _res_heat, _res_heat_range, _Temperature, BME680_CONTROL_GAS_REGISTER1, BME680_CONTROL_GAS_REGISTER2, BME680_GAS_DURATION_REGISTER0, BME680_GAS_HEATER_REGISTER0, putData(), readByte(), waitForReadings(), and wire.
setIIRFilter()
uint8_t BME680_Class::setIIRFilter (const uint8_t iirFilterSetting = UINT8_MAX)
Set or return the current IIR filter setting
When called with no parameters returns the current IIR Filter setting, otherwise when called with one parameter will set the IIR filter value and return the new setting param[in] iirFilterSetting New setting return IIR Filter setting
Definition at line 425 of file BME680.cpp.
{
    waitForReadings(); // Ensure any active reading is finished
    uint8_t returnValue =
        readByte(BME680_CONFIG_REGISTER); // Get control register byte contents
    if (iirFilterSetting != UINT8_MAX)    // If the value is to be changed
    {                                     //
        returnValue = returnValue & B11100011; // mask IIR bits
        returnValue |= (iirFilterSetting & B00000111)
                       << 2; // use 3 bits of iirFilterSetting
        putData(wire, BME680_CONFIG_REGISTER,
                returnValue); // Write new control register value
    } // if the value is to be changed                                   //
    returnValue = (returnValue >> 2) &
                  B00000111; // Extract IIR filter setting from register
    return (returnValue);    // Return IIR Filter setting
} // of method setIIRFilter()
References BME680_CONFIG_REGISTER, putData(), readByte(), waitForReadings(), and wire.
setOversampling()
uint8_t BME680_Class::setOversampling (const uint8_t sensor, const uint8_t sampling = UINT8_MAX)
sets the oversampling mode for the sensor
See enumerated "sensorTypes" for a list of values. Set to a valid oversampling rate as defined in the enumerated type oversamplingTypes. If either value is out of range or another error occurs then the return value is false. param[in] sensor Enumerated sensor type param[in] sampling Sampling rate from enumerated type return "true" if successful otherwise false
Definition at line 352 of file BME680.cpp.
{
    if (sensor >= UnknownSensor ||
        (sampling != UINT8_MAX &&
         sampling >= UnknownOversample)) { // return an error if sensor or
                                           // oversample is out of range
        return (UINT8_MAX);
    }
    uint8_t tempRegister;           // Temporary register variable
    uint8_t returnValue = sampling; // Return sampling value
    waitForReadings();              // Ensure any active reading is finished
    switch (sensor) {               // Depending upon which sensor is chosen
    case HumiditySensor:            // Set the humidity oversampling
    {
        tempRegister = readByte(
            BME680_CONTROL_HUMIDITY_REGISTER); // Read the register contents
        if (sampling == UINT8_MAX) {           // If we just want to read values
            returnValue =
                tempRegister & ~BME680_HUMIDITY_MASK; // Set return value
        } else {
            tempRegister &= BME680_HUMIDITY_MASK; // Mask bits to 0
            tempRegister |= sampling;             // Add in the sampling bits
            putData(wire, BME680_CONTROL_HUMIDITY_REGISTER,
                    (uint8_t)tempRegister); // Update humidity bits 0:2
        } // if-then return current value or set new value
        break;
    } // of HumiditySensor
    case PressureSensor: // Set the pressure oversampling
    {
        tempRegister = readByte(
            BME680_CONTROL_MEASURE_REGISTER); // Read the register contents
        if (sampling == UINT8_MAX) { // If we just want to read the values
            returnValue =
                (tempRegister & ~BME680_PRESSURE_MASK) >> 2; // Set return value
        } else {
            tempRegister &= BME680_PRESSURE_MASK; // Mask bits to 0
            tempRegister |= (sampling << 2); // Add in sampling bits at offset
            putData(wire, BME680_CONTROL_MEASURE_REGISTER,
                    (uint8_t)tempRegister); // Update register
        } // if-then return current value or set new value
        break;
    } // of PressureSensor
    case TemperatureSensor: // Set the temperature oversampling
    {
        tempRegister = readByte(
            BME680_CONTROL_MEASURE_REGISTER); // Read the register contents
        if (sampling == UINT8_MAX) { // If we just want to read the values
            returnValue = (tempRegister & ~BME680_TEMPERATURE_MASK) >>
                          5; // Set return value
        } else {
            tempRegister &= BME680_TEMPERATURE_MASK; // Mask bits to 0
            tempRegister |=
                (sampling << 5); // Add in the sampling bits at offset
            putData(wire, BME680_CONTROL_MEASURE_REGISTER,
                    (uint8_t)tempRegister); // Update humidity bits 5:7
        } // if-then return current value or set new value
        break;
    } // of TemperatureSensor
    default:
        return (UINT8_MAX); // Return an error if no match
    } // of switch the sensor type
    return (returnValue); // Otherwise return current value
} // of method setOversampling()
References BME680_CONTROL_HUMIDITY_REGISTER, BME680_CONTROL_MEASURE_REGISTER, BME680_HUMIDITY_MASK, BME680_PRESSURE_MASK, BME680_TEMPERATURE_MASK, HumiditySensor, PressureSensor, putData(), readByte(), TemperatureSensor, UnknownOversample, UnknownSensor, waitForReadings(), and wire.
triggerMeasurement()
void BME680_Class::triggerMeasurement ()
trigger a measurement
Trigger a new measurement on the BME680
Definition at line 670 of file BME680.cpp.
{
    uint8_t workRegister =
        readByte(BME680_CONTROL_MEASURE_REGISTER); // Read the control measure
    putData(wire, BME680_CONTROL_MEASURE_REGISTER,
            (uint8_t)(workRegister | 1)); // Trigger start of next measurement
} // of method "triggerMeasurement()"
References BME680_CONTROL_MEASURE_REGISTER, putData(), readByte(), and wire.
Referenced by readSensors().
waitForReadings()
void BME680_Class::waitForReadings () private
Wait for readings to finish.
Only returns once a measurement on the BME680 has completed
Definition at line 595 of file BME680.cpp.
{
    while (measuring()) {
    } // loop until any active measurment is complete
} // of method waitForReadings
References measuring().
Referenced by readSensors(), setGas(), setIIRFilter(), and setOversampling().
Member Data Documentation
_cs
uint8_t BME680_Class::_cs private
Definition at line 187 of file BME680.h.
Referenced by begin(), begin(), getData(), putData(), and reset().
_G1
int8_t BME680_Class::_G1 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and setGas().
_G2
int16_t BME680_Class::_G2 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and setGas().
_G3
int8_t BME680_Class::_G3 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration().
_Gas
int32_t BME680_Class::_Gas private
signed 32bit configuration vars
Definition at line 195 of file BME680.h.
Referenced by getSensorData(), and readSensors().
_H1
uint16_t BME680_Class::_H1 private
Definition at line 191 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_H2
uint16_t BME680_Class::_H2 private
Definition at line 191 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_H3
int8_t BME680_Class::_H3 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), readSensors(), and setGas().
_H4
int8_t BME680_Class::_H4 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_H5
int8_t BME680_Class::_H5 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_H6
uint8_t BME680_Class::_H6 private
Definition at line 188 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_H7
int8_t BME680_Class::_H7 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_Humidity
int32_t BME680_Class::_Humidity private
Definition at line 194 of file BME680.h.
Referenced by getSensorData(), and readSensors().
_I2CAddress
uint8_t BME680_Class::_I2CAddress = 0 private
Default is I2C address is unknown.
Definition at line 185 of file BME680.h.
Referenced by begin(), commonInitialization(), getData(), getI2CAddress(), putData(), and reset().
_I2CSpeed
uint16_t BME680_Class::_I2CSpeed = 0 private
Default is I2C speed is unknown.
Definition at line 186 of file BME680.h.
Referenced by begin(), and reset().
_miso
uint8_t BME680_Class::_miso private
Hardware and software SPI pins.
Definition at line 187 of file BME680.h.
Referenced by begin(), getData(), and reset().
_mosi
uint8_t BME680_Class::_mosi private
Definition at line 187 of file BME680.h.
Referenced by begin(), getData(), putData(), and reset().
_P1
uint16_t BME680_Class::_P1 private
unsigned 16bit configuration vars
Definition at line 191 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P10
uint8_t BME680_Class::_P10 private
Definition at line 188 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P2
int16_t BME680_Class::_P2 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P3
int8_t BME680_Class::_P3 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P4
int16_t BME680_Class::_P4 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P5
int16_t BME680_Class::_P5 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P6
int8_t BME680_Class::_P6 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P7
int8_t BME680_Class::_P7 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P8
int16_t BME680_Class::_P8 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_P9
int16_t BME680_Class::_P9 private
signed 16bit configuration vars
Definition at line 193 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_Pressure
int32_t BME680_Class::_Pressure private
Definition at line 194 of file BME680.h.
Referenced by getSensorData(), and readSensors().
_res_heat
int8_t BME680_Class::_res_heat private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and setGas().
_res_heat_range
uint8_t BME680_Class::_res_heat_range private
unsigned configuration vars
Definition at line 188 of file BME680.h.
Referenced by getCalibration(), and setGas().
_rng_sw_err
int8_t BME680_Class::_rng_sw_err private
signed configuration vars
Definition at line 190 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_sck
uint8_t BME680_Class::_sck private
Definition at line 187 of file BME680.h.
Referenced by begin(), getData(), putData(), and reset().
_T1
uint16_t BME680_Class::_T1 private
Definition at line 191 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_T2
int16_t BME680_Class::_T2 private
Definition at line 192 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_T3
int8_t BME680_Class::_T3 private
Definition at line 189 of file BME680.h.
Referenced by getCalibration(), and readSensors().
_Temperature
int32_t BME680_Class::_Temperature private
Definition at line 194 of file BME680.h.
Referenced by getSensorData(), readSensors(), and setGas().
_tfine
int32_t BME680_Class::_tfine private
Definition at line 194 of file BME680.h.
Referenced by readSensors().
wire
TwoWire BME680_Class::wire = TwoWire(1) private
Definition at line 150 of file BME680.h.
Referenced by begin(), commonInitialization(), getCalibration(), getData(), putData(), readByte(), readSensors(), reset(), setGas(), setIIRFilter(), setOversampling(), and triggerMeasurement().
The documentation for this class was generated from the following files:
BME680.h
BME680.cpp