microClimate Monitoring Remote Node [Firmware]: firmware.ino File Reference
firmware.ino File Reference
#include "SensorInterface.h"
#include "display.h"
#include "lora_config.h"
#include <Arduino.h>
#include <LoRaWan_APP.h>
Macros
#define BAUD 115200
Functions
static void on_tx_done ()
static void on_tx_timeout ()
static void on_rx_done (uint8_t *payload, uint16_t size, int16_t rssi, int8_t snr)
void setup ()
static void showTime ()
static void drawBanner ()
static void drawNetwork ()
static void drawSensors (int32_t t, int32_t h, int32_t p, int32_t g)
static void renderDashboard (int32_t t, int32_t h, int32_t p, int32_t g)
void loop ()
Variables
static OledDisplay oledDisplay
static RadioEvents_t radioEvents
static SensorInterface sensorInterface
static int16_t lastRssi = 0
static int8_t lastSNR = 0
static uint8_t counter = 0
static char buffer [64]
Macro Definition Documentation
BAUD
#define BAUD 115200
Definition at line 7 of file firmware.ino.
Referenced by setup().
Function Documentation
drawBanner()
void drawBanner () static
Definition at line 84 of file firmware.ino.
{ oledDisplay.write(0, 0, " ENV MONITOR "); }
References oledDisplay.
Referenced by renderDashboard().
drawNetwork()
void drawNetwork () static
Definition at line 86 of file firmware.ino.
{
  sprintf(buffer, "RSSI:%d | SNR: %d", lastRssi, lastSNR);
  oledDisplay.write(0, 4, buffer);
}
References buffer, lastRssi, lastSNR, and oledDisplay.
Referenced by renderDashboard().
drawSensors()
void drawSensors (int32_t t, int32_t h, int32_t p, int32_t g) static
Definition at line 91 of file firmware.ino.
{
  sprintf(buffer, "T:%d.%02dC | H:%d.%03d%%", t / 100, abs(t % 100), h / 1000,
          abs(h % 1000));
  oledDisplay.write(0, 1, buffer);
  sprintf(buffer, "P:%d.%03dkPa", p / 1000, abs(p % 1000));
  oledDisplay.write(0, 2, buffer);
  sprintf(buffer, "G:%d.%02d", g / 100, abs(g % 100));
  oledDisplay.write(0, 3, buffer);
}
References buffer, and oledDisplay.
Referenced by renderDashboard().
loop()
void loop ()
Definition at line 112 of file firmware.ino.
            {
  static int32_t temp, humidity, pressure, gas;
  sensorInterface.getSensorData(temp, humidity, pressure, gas);
  renderDashboard(temp, humidity, pressure, gas);
  Radio.IrqProcess();
  delay(1000);
}
References renderDashboard(), and sensorInterface.
on_rx_done()
void on_rx_done (uint8_t * payload, uint16_t size, int16_t rssi, int8_t snr) static
Definition at line 18 of file firmware.ino.
{
  lastRssi = rssi;
  lastSNR = snr;
  Serial.printf("A frame sized %d was received.\n", size);
}
References lastRssi, and lastSNR.
Referenced by setup().
on_tx_done()
void on_tx_done () static
Definition at line 16 of file firmware.ino.
{ Radio.Rx(0); }
Referenced by setup().
on_tx_timeout()
void on_tx_timeout () static
Definition at line 17 of file firmware.ino.
{ Radio.Rx(0); }
Referenced by setup().
renderDashboard()
void renderDashboard (int32_t t, int32_t h, int32_t p, int32_t g) static
Definition at line 103 of file firmware.ino.
{
  oledDisplay.clear();
  drawBanner();
  drawSensors(t, h, p, g);
  drawNetwork();
  showTime();
  oledDisplay.commit();
}
References drawBanner(), drawNetwork(), drawSensors(), oledDisplay, and showTime().
Referenced by loop().
setup()
void setup ()
Definition at line 25 of file firmware.ino.
             {
  Serial.begin(BAUD);
  // delay(5000); // TODO: remove this in deployment (in place just to wait for
  //  serial monitor to connect)
  Mcu.begin(HELTEC_BOARD, SLOW_CLK_TPYE);
  Serial.print("Connecting to the sensor...");
  while (!sensorInterface.init()) {
    Serial.println("- Trying to connect to the Sensor in 5 minutes.");
    delay(5000);
  }
  Serial.println("(done)");
  Serial.print("Initializing oledDisplay...");
  oledDisplay.init(); // initialize the display
  Serial.println("(done)");
  oledDisplay.info(); // show the info of the display pins in the serial
  Serial.print("Setting radio configurations...");
  /* set callbacks for radio events */
  radioEvents.TxDone = on_tx_done;
  radioEvents.TxTimeout = on_tx_timeout;
  radioEvents.RxDone = on_rx_done;
  /* configure the LoRa Radio Object */
  Radio.Init(&radioEvents);
  Radio.SetChannel(RF_FREQUENCY);
  Radio.SetTxConfig(MODEM_LORA, TX_OUTPUT_POWER, 0, LORA_BANDWIDTH,
                    LORA_SPREADING_FACTOR, LORA_CODINGRATE,
                    LORA_PREAMBLE_LENGTH, LORA_FIX_LENGTH_PAYLOAD_ON, true, 0,
                    0, LORA_IQ_INVERSION_ON, 3000);
  Radio.SetRxConfig(MODEM_LORA, LORA_BANDWIDTH, LORA_SPREADING_FACTOR,
                    LORA_CODINGRATE, 0, LORA_PREAMBLE_LENGTH,
                    LORA_FIX_LENGTH_PAYLOAD_ON, 0, true, 0, 0,
                    LORA_IQ_INVERSION_ON, true, RX_TIMEOUT_VALUE);
  Serial.println("(done)");
  Radio.Rx(0);
  delay(2000);
  oledDisplay.clear();
  oledDisplay.commit();
}
References BAUD, LORA_BANDWIDTH, LORA_CODINGRATE, LORA_FIX_LENGTH_PAYLOAD_ON, LORA_IQ_INVERSION_ON, LORA_PREAMBLE_LENGTH, LORA_SPREADING_FACTOR, oledDisplay, on_rx_done(), on_tx_done(), on_tx_timeout(), radioEvents, RF_FREQUENCY, RX_TIMEOUT_VALUE, sensorInterface, and TX_OUTPUT_POWER.
showTime()
void showTime () static
Definition at line 73 of file firmware.ino.
                       {
  uint32_t uptime = millis() / 1000; // seconds since boot
  uint32_t hours = uptime / 3600;
  uint32_t minutes = (uptime % 3600) / 60;
  uint32_t seconds = uptime % 60;
  sprintf(buffer, "U: %02d:%02d:%02d", hours, minutes, seconds);
  oledDisplay.write(5, 3, buffer);
}
References buffer, and oledDisplay.
Referenced by renderDashboard().
Variable Documentation
buffer
char buffer[64] static
Definition at line 71 of file firmware.ino.
Referenced by drawNetwork(), drawSensors(), and showTime().
counter
uint8_t counter = 0 static
Definition at line 70 of file firmware.ino.
lastRssi
int16_t lastRssi = 0 static
Definition at line 13 of file firmware.ino.
Referenced by drawNetwork(), and on_rx_done().
lastSNR
int8_t lastSNR = 0 static
Definition at line 14 of file firmware.ino.
Referenced by drawNetwork(), and on_rx_done().
oledDisplay
OledDisplay oledDisplay static
Definition at line 9 of file firmware.ino.
Referenced by drawBanner(), drawNetwork(), drawSensors(), renderDashboard(), setup(), and showTime().
radioEvents
RadioEvents_t radioEvents static
Definition at line 10 of file firmware.ino.
Referenced by setup().
sensorInterface
SensorInterface sensorInterface static
Definition at line 11 of file firmware.ino.
Referenced by loop(), and setup().